# enable Link Time optimization
EXTRAFLAGS += -flto
VIA_ENABLE = yes
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
ENCODER_MAP_ENABLE = no
CONSOLE_ENABLE = no
